theme: jekyll-theme-minimal
title: Allison Keith
description: my portfolio

navigation_header:
  - title: Home
    url: https://allisonakeith.github.io/
  - title: Publications
    url: https://allisonakeith.github.io/about/Publications/
  - title: Blog
    url: https://allisonakeith.github.io/about/blog/
  - title: Categories
    url: https://allisonakeith.github.io/about/categories/
  - title: Search
    url: https://allisonakeith.github.io/about/search/
  - title: About
    url: https://allisonakeith.github.io/about/about/

navigation_footer:
  - title: Created by me
    url:
